const schemes = [
  {
    name: 'PM-KISAN Samman Nidhi', benefit: '₹6,000/year', status: 'Active',
    desc: 'Direct income support of ₹6,000 per year to eligible farmer families, paid in 3 installments.',
    descHi: 'पात्र किसान परिवारों को ₹6,000 प्रति वर्ष की प्रत्यक्ष आय सहायता, 3 किस्तों में भुगतान।',
    elig: 'All farmer families with cultivable land',
    eligHi: 'खेती योग्य भूमि वाले सभी किसान परिवार',
    docs: ['Aadhaar Card', 'Land Records', 'Bank Passbook'],
    ministry: 'Ministry of Agriculture', deadline: '31 Mar 2027',
    applyUrl: 'https://pmkisan.gov.in',
    steps: [
      { en: 'Visit pmkisan.gov.in and click "New Farmer Registration"', hi: 'pmkisan.gov.in पर जाएं और "New Farmer Registration" पर क्लिक करें' },
      { en: 'Select Rural/Urban farmer type and enter your Aadhaar number', hi: 'ग्रामीण/शहरी किसान प्रकार चुनें और अपना आधार नंबर दर्ज करें' },
      { en: 'Enter your State, District, Sub-District, and Village', hi: 'अपना राज्य, जिला, उप-जिला और गांव दर्ज करें' },
      { en: 'Fill personal details — Full Name (as per Aadhaar), Category (SC/ST/OBC/General)', hi: 'व्यक्तिगत विवरण भरें — पूरा नाम (आधार के अनुसार), श्रेणी (SC/ST/OBC/सामान्य)' },
      { en: 'Enter Bank Account Number and IFSC Code (from your passbook)', hi: 'बैंक खाता नंबर और IFSC कोड दर्ज करें (पासबुक से)' },
      { en: 'Enter land details — Khata Number, Survey/Dag Number, Area in Hectares', hi: 'भूमि विवरण दर्ज करें — खाता नंबर, सर्वे/दाग नंबर, क्षेत्रफल हेक्टेयर में' },
      { en: 'Upload scanned Aadhaar Card and Land Ownership document (Khatauni/7-12)', hi: 'स्कैन किया हुआ आधार कार्ड और भूमि स्वामित्व दस्तावेज़ (खतौनी/7-12) अपलोड करें' },
      { en: 'Verify your mobile number via OTP sent to your registered number', hi: 'अपने पंजीकृत नंबर पर भेजे गए OTP से मोबाइल नंबर सत्यापित करें' },
      { en: 'Review all details and click "Submit". Note your Registration Number', hi: 'सभी विवरण जांचें और "Submit" क्लिक करें। अपना पंजीकरण नंबर नोट करें' },
      { en: 'Your application will be verified by State/District officer. Check status on the portal.', hi: 'आपका आवेदन राज्य/जिला अधिकारी द्वारा सत्यापित होगा। पोर्टल पर स्थिति जांचें।' },
      { en: 'Once approved, ₹2,000 will be credited to your bank every 4 months', hi: 'स्वीकृति के बाद, हर 4 महीने में ₹2,000 आपके बैंक खाते में जमा होगा' },
    ],
  },
  {
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)', benefit: 'Crop Insurance', status: 'Active',
    desc: 'Crop insurance at affordable premiums — Kharif 2%, Rabi 1.5%. Covers natural calamities, pests, diseases.',
    descHi: 'सस्ती प्रीमियम पर फसल बीमा — खरीफ 2%, रबी 1.5%। प्राकृतिक आपदाओं, कीटों, रोगों से सुरक्षा।',
    elig: 'All farmers growing notified crops (loanee & non-loanee)',
    eligHi: 'अधिसूचित फसलें उगाने वाले सभी किसान (ऋणी और गैर-ऋणी)',
    docs: ['Land Records', 'Sowing Certificate', 'Bank Account', 'Aadhaar'],
    ministry: 'Ministry of Agriculture', deadline: '31 Jul 2026',
    applyUrl: 'https://pmfby.gov.in',
    steps: [
      { en: 'Visit pmfby.gov.in and click "Farmer Corner" on top menu', hi: 'pmfby.gov.in पर जाएं और ऊपर "Farmer Corner" क्लिक करें' },
      { en: 'Click "Guest Farmer" to register or login if already registered', hi: '"Guest Farmer" पर क्लिक करके रजिस्टर करें या पहले से रजिस्टर हैं तो लॉगिन करें' },
      { en: 'Register with Mobile Number → Enter OTP → Set Password', hi: 'मोबाइल नंबर से रजिस्टर करें → OTP दर्ज करें → पासवर्ड सेट करें' },
      { en: 'After login, click "Apply for Crop Insurance"', hi: 'लॉगिन के बाद "Apply for Crop Insurance" पर क्लिक करें' },
      { en: 'Select Season (Kharif/Rabi), Year, State, District, Block, Village', hi: 'सीजन (खरीफ/रबी), वर्ष, राज्य, जिला, ब्लॉक, गांव चुनें' },
      { en: 'Select your Crop from the notified crop list for your area', hi: 'अपने क्षेत्र की अधिसूचित फसल सूची से अपनी फसल चुनें' },
      { en: 'Enter land area sown (in hectares) and land type (owned/leased)', hi: 'बोई गई भूमि का क्षेत्रफल (हेक्टेयर में) और भूमि प्रकार (स्वामित्व/पट्टा) दर्ज करें' },
      { en: 'Upload Land Record (Khatauni) and Sowing Certificate from Patwari', hi: 'भूमि रिकॉर्ड (खतौनी) और पटवारी से बुवाई प्रमाण पत्र अपलोड करें' },
      { en: 'Enter Bank Account & IFSC. Pay premium online (Kharif 2% of sum insured)', hi: 'बैंक खाता और IFSC दर्ज करें। प्रीमियम ऑनलाइन भुगतान करें (खरीफ: बीमा राशि का 2%)' },
      { en: 'Download your Policy Document after successful payment', hi: 'सफल भुगतान के बाद अपना पॉलिसी दस्तावेज़ डाउनलोड करें' },
    ],
  },
  {
    name: 'Kisan Credit Card (KCC)', benefit: 'Credit at 4%', status: 'Active',
    desc: 'Short-term credit at 4% interest up to ₹3 lakh. No collateral up to ₹1.6 lakh.',
    descHi: '₹3 लाख तक 4% ब्याज पर अल्पकालीन ऋण। ₹1.6 लाख तक कोई गारंटी नहीं।',
    elig: 'All farmers, sharecroppers, tenant farmers, SHGs',
    eligHi: 'सभी किसान, बटाईदार, किरायेदार किसान, स्वयं सहायता समूह',
    docs: ['Land Records/Lease', 'Aadhaar', 'PAN Card', 'Passport Photo'],
    ministry: 'Ministry of Finance', deadline: 'Ongoing',
    applyUrl: 'https://www.myscheme.gov.in/schemes/kcc',
    steps: [
      { en: 'Visit pmkisan.gov.in/kccform OR go to nearest Bank (SBI/PNB/Cooperative)', hi: 'pmkisan.gov.in/kccform पर जाएं या नजदीकी बैंक (SBI/PNB/सहकारी) जाएं' },
      { en: 'If online: Login to PM-KISAN portal with your registered mobile number', hi: 'ऑनलाइन: PM-KISAN पोर्टल पर अपने पंजीकृत मोबाइल नंबर से लॉगिन करें' },
      { en: 'Click on "KCC Form" → Download the application form (PDF)', hi: '"KCC Form" पर क्लिक करें → आवेदन फॉर्म (PDF) डाउनलोड करें' },
      { en: 'Fill the form: Name, Father\'s Name, Age, Address, Land details', hi: 'फॉर्म भरें: नाम, पिता का नाम, उम्र, पता, भूमि विवरण' },
      { en: 'Attach: Land ownership docs (Khatauni/7-12), Aadhaar copy, PAN copy, 2 photos', hi: 'संलग्न करें: भूमि स्वामित्व दस्तावेज़ (खतौनी/7-12), आधार कॉपी, PAN कॉपी, 2 फोटो' },
      { en: 'Submit the form at your bank branch. Get acknowledgment receipt.', hi: 'अपनी बैंक शाखा में फॉर्म जमा करें। पावती रसीद लें।' },
      { en: 'Bank will verify documents and assess credit limit (based on land & crops)', hi: 'बैंक दस्तावेज़ सत्यापित करेगा और ऋण सीमा निर्धारित करेगा (भूमि और फसल के आधार पर)' },
      { en: 'KCC issued within 14 working days. Credit limit up to ₹3 lakh at 4% interest.', hi: 'KCC 14 कार्य दिवसों में जारी। ₹3 लाख तक ऋण सीमा 4% ब्याज पर।' },
      { en: 'Repay loan within crop season to avail 3% interest subvention benefit', hi: 'फसल सीजन में ऋण चुकाएं और 3% ब्याज छूट का लाभ उठाएं' },
    ],
  },
  {
    name: 'Soil Health Card Scheme', benefit: 'Free Soil Testing', status: 'Active',
    desc: 'Free soil testing and health cards with nutrient status and fertilizer recommendations.',
    descHi: 'मुफ्त मिट्टी परीक्षण और पोषक तत्व स्थिति व उर्वरक सिफारिशों के साथ स्वास्थ्य कार्ड।',
    elig: 'All farmers', eligHi: 'सभी किसान',
    docs: ['Aadhaar Card', 'Land Details'],
    ministry: 'Ministry of Agriculture', deadline: 'Ongoing',
    applyUrl: 'https://soilhealth.dac.gov.in',
    steps: [
      { en: 'Visit soilhealth.dac.gov.in and click "Register"', hi: 'soilhealth.dac.gov.in पर जाएं और "Register" क्लिक करें' },
      { en: 'Select State, District → Enter Mobile Number → Get OTP', hi: 'राज्य, जिला चुनें → मोबाइल नंबर दर्ज करें → OTP प्राप्त करें' },
      { en: 'Create your account with Name, Aadhaar, Village, and Password', hi: 'नाम, आधार, गांव और पासवर्ड से अपना खाता बनाएं' },
      { en: 'Login and click "Sample Registration" to request soil testing', hi: 'लॉगिन करें और मिट्टी परीक्षण के लिए "Sample Registration" पर क्लिक करें' },
      { en: 'Enter farm details — Survey Number, GPS Location, Crop grown', hi: 'खेत का विवरण दर्ज करें — सर्वे नंबर, GPS स्थान, उगाई गई फसल' },
      { en: 'Soil testing team will collect sample from your field within 2 weeks', hi: 'मिट्टी परीक्षण टीम 2 सप्ताह में आपके खेत से नमूना एकत्र करेगी' },
      { en: 'Results tested for 12 parameters (N, P, K, pH, Organic Carbon etc.)', hi: '12 मापदंडों (N, P, K, pH, जैविक कार्बन आदि) के लिए परीक्षण' },
      { en: 'View/Download your Soil Health Card from portal after 2-3 weeks', hi: '2-3 सप्ताह बाद पोर्टल से अपना मृदा स्वास्थ्य कार्ड देखें/डाउनलोड करें' },
    ],
  },
  {
    name: 'PM Krishi Sinchai Yojana', benefit: 'Irrigation Subsidy 55%', status: 'Active',
    desc: 'Micro-irrigation (drip & sprinkler) subsidy up to 55% for small farmers.',
    descHi: 'छोटे किसानों के लिए सूक्ष्म सिंचाई (ड्रिप और स्प्रिंकलर) पर 55% तक सब्सिडी।',
    elig: 'All farmers with own/leased land', eligHi: 'स्वामित्व/पट्टे पर भूमि वाले सभी किसान',
    docs: ['Land Records', 'Aadhaar', 'Bank Account', 'Vendor Quotation'],
    ministry: 'Ministry of Agriculture', deadline: '31 Mar 2027',
    applyUrl: 'https://pmksy.mowr.gov.in',
    steps: [
      { en: 'Visit pmksy.gov.in OR contact District Agriculture Office', hi: 'pmksy.gov.in पर जाएं या जिला कृषि कार्यालय से संपर्क करें' },
      { en: 'Register on the portal with Aadhaar, Mobile, and Land details', hi: 'पोर्टल पर आधार, मोबाइल और भूमि विवरण से रजिस्टर करें' },
      { en: 'Select scheme component: Drip Irrigation / Sprinkler System', hi: 'योजना घटक चुनें: ड्रिप सिंचाई / स्प्रिंकलर प्रणाली' },
      { en: 'Get quotation from empaneled vendor (list available on portal)', hi: 'सूचीबद्ध विक्रेता से कोटेशन लें (सूची पोर्टल पर उपलब्ध)' },
      { en: 'Upload: Land documents, Aadhaar, Bank Passbook, Vendor Quotation', hi: 'अपलोड करें: भूमि दस्तावेज़, आधार, बैंक पासबुक, विक्रेता कोटेशन' },
      { en: 'Department verifies and approves subsidy (55% small farmer, 45% others)', hi: 'विभाग सत्यापित करेगा और सब्सिडी स्वीकृत करेगा (छोटे किसान 55%, अन्य 45%)' },
      { en: 'Install the system. Get verification visit from department inspector.', hi: 'सिस्टम स्थापित करें। विभाग निरीक्षक से सत्यापन विजिट करवाएं।' },
      { en: 'Subsidy credited to bank within 30 days of verification', hi: 'सत्यापन के 30 दिनों में सब्सिडी बैंक खाते में जमा' },
    ],
  },
  {
    name: 'E-NAM (National Agriculture Market)', benefit: 'Online Mandi', status: 'Active',
    desc: 'Sell produce online to buyers across India — transparent pricing, no middlemen.',
    descHi: 'पूरे भारत में खरीदारों को ऑनलाइन उपज बेचें — पारदर्शी मूल्य, कोई बिचौलिया नहीं।',
    elig: 'All farmers with mandi registration', eligHi: 'मंडी पंजीकरण वाले सभी किसान',
    docs: ['Aadhaar', 'Mandi Registration', 'Bank Account'],
    ministry: 'Ministry of Agriculture', deadline: 'Ongoing',
    applyUrl: 'https://www.enam.gov.in',
    steps: [
      { en: 'Visit enam.gov.in → Click "Registration" → Select "Farmer"', hi: 'enam.gov.in पर जाएं → "Registration" क्लिक करें → "Farmer" चुनें' },
      { en: 'Enter Mobile Number → Verify with OTP → Set Password', hi: 'मोबाइल नंबर दर्ज करें → OTP से सत्यापित करें → पासवर्ड सेट करें' },
      { en: 'Fill: Name, Aadhaar, State, APMC Mandi, Bank Account + IFSC', hi: 'भरें: नाम, आधार, राज्य, APMC मंडी, बैंक खाता + IFSC' },
      { en: 'Upload Aadhaar and Mandi Registration/License document', hi: 'आधार और मंडी पंजीकरण/लाइसेंस दस्तावेज़ अपलोड करें' },
      { en: 'Get your e-NAM Farmer ID after verification (1-2 days)', hi: 'सत्यापन के बाद अपना e-NAM किसान ID प्राप्त करें (1-2 दिन)' },
      { en: 'Login → Click "Sell" → Enter commodity, quantity, quality grade', hi: 'लॉगिन → "Sell" क्लिक → कमोडिटी, मात्रा, गुणवत्ता ग्रेड दर्ज करें' },
      { en: 'Buyers from across India bid on your produce online', hi: 'पूरे भारत के खरीदार आपकी उपज पर ऑनलाइन बोली लगाते हैं' },
      { en: 'Accept best bid → Payment transferred to your bank account', hi: 'सर्वोत्तम बोली स्वीकार करें → भुगतान आपके बैंक खाते में' },
    ],
  },
  {
    name: 'Agriculture Infrastructure Fund', benefit: '3% Interest Subvention', status: 'Active',
    desc: '₹1 lakh crore for cold storage, warehouses, processing units. 3% interest subvention for 7 years.',
    descHi: 'कोल्ड स्टोरेज, गोदाम, प्रसंस्करण इकाइयों के लिए ₹1 लाख करोड़। 7 वर्ष के लिए 3% ब्याज छूट।',
    elig: 'Farmers, FPOs, PACS, Agri-entrepreneurs', eligHi: 'किसान, FPO, PACS, कृषि-उद्यमी',
    docs: ['Project Report', 'Land/Lease', 'Bank Account', 'Aadhaar'],
    ministry: 'Ministry of Agriculture', deadline: '31 Mar 2027',
    applyUrl: 'https://agriinfra.dac.gov.in',
    steps: [
      { en: 'Visit agriinfra.dac.gov.in → Click "Beneficiary Registration"', hi: 'agriinfra.dac.gov.in → "Beneficiary Registration" क्लिक करें' },
      { en: 'Register with PAN, Aadhaar, Mobile → Verify OTP', hi: 'PAN, आधार, मोबाइल से रजिस्टर करें → OTP सत्यापित करें' },
      { en: 'Select beneficiary type: Individual Farmer / FPO / PACS', hi: 'लाभार्थी प्रकार चुनें: व्यक्तिगत किसान / FPO / PACS' },
      { en: 'Prepare Detailed Project Report (DPR) with cost breakdown', hi: 'विस्तृत परियोजना रिपोर्ट (DPR) लागत विवरण के साथ तैयार करें' },
      { en: 'Submit application online with DPR, land/lease docs, bank details', hi: 'DPR, भूमि/पट्टा दस्तावेज़, बैंक विवरण के साथ ऑनलाइन आवेदन जमा करें' },
      { en: 'Select lending bank from the participating bank list on portal', hi: 'पोर्टल पर भाग लेने वाले बैंकों की सूची से ऋण बैंक चुनें' },
      { en: 'Bank processes loan with CGTMSE credit guarantee cover', hi: 'बैंक CGTMSE क्रेडिट गारंटी कवर के साथ ऋण प्रक्रिया करेगा' },
      { en: '3% interest subvention applied automatically for 7 years', hi: '7 वर्ष के लिए 3% ब्याज छूट स्वचालित रूप से लागू' },
    ],
  },
  {
    name: 'Paramparagat Krishi Vikas Yojana', benefit: '₹50,000/ha', status: 'Active',
    desc: '₹50,000 per hectare for 3 years for organic farming — training, certification, marketing.',
    descHi: 'जैविक खेती के लिए 3 वर्ष तक ₹50,000 प्रति हेक्टेयर — प्रशिक्षण, प्रमाणन, विपणन।',
    elig: 'Farmers willing to adopt organic farming in clusters',
    eligHi: 'क्लस्टर में जैविक खेती अपनाने वाले किसान',
    docs: ['Land Records', 'Aadhaar', 'Bank Account'],
    ministry: 'Ministry of Agriculture', deadline: '31 Dec 2026',
    applyUrl: 'https://pgsindia-ncof.gov.in/pkvy/index.aspx',
    steps: [
      { en: 'Form a cluster of 50+ farmers covering at least 50 acres', hi: 'कम से कम 50 एकड़ में 50+ किसानों का क्लस्टर बनाएं' },
      { en: 'Visit pgsindia-ncof.gov.in or contact District Agriculture Officer', hi: 'pgsindia-ncof.gov.in पर जाएं या जिला कृषि अधिकारी से संपर्क करें' },
      { en: 'Register the cluster with list of participating farmers + land details', hi: 'भाग लेने वाले किसानों + भूमि विवरण की सूची के साथ क्लस्टर पंजीकृत करें' },
      { en: 'Each farmer submits Aadhaar, land records, bank account details', hi: 'प्रत्येक किसान आधार, भूमि रिकॉर्ड, बैंक खाता विवरण जमा करे' },
      { en: 'Attend organic farming training sessions conducted under the scheme', hi: 'योजना के तहत आयोजित जैविक खेती प्रशिक्षण सत्रों में भाग लें' },
      { en: 'Adopt organic practices — stop chemical fertilizers and pesticides', hi: 'जैविक तरीके अपनाएं — रासायनिक उर्वरक और कीटनाशक बंद करें' },
      { en: 'Get PGS certification for your organic produce', hi: 'अपनी जैविक उपज के लिए PGS प्रमाणन प्राप्त करें' },
      { en: '₹50,000/ha disbursed over 3 years to your bank account', hi: '₹50,000/हेक्टेयर 3 वर्षों में आपके बैंक खाते में वितरित' },
    ],
  },
  {
    name: 'PM Kisan Maandhan Yojana', benefit: '₹3,000/month pension', status: 'Active',
    desc: 'Voluntary pension scheme for small/marginal farmers. Contribute ₹55-200/month, get ₹3,000/month pension after age 60.',
    descHi: 'छोटे/सीमांत किसानों के लिए स्वैच्छिक पेंशन योजना। ₹55-200/माह का योगदान करें, 60 वर्ष बाद ₹3,000/माह पेंशन पाएं।',
    elig: 'Small/marginal farmers age 18-40 with less than 2 hectares',
    eligHi: '2 हेक्टेयर से कम भूमि वाले 18-40 वर्ष के छोटे/सीमांत किसान',
    docs: ['Aadhaar Card', 'Bank Account', 'Land Records', 'Age Proof'],
    ministry: 'Ministry of Agriculture', deadline: 'Ongoing',
    applyUrl: 'https://maandhan.in',
    steps: [
      { en: 'Visit maandhan.in and click "Click here to apply now"', hi: 'maandhan.in पर जाएं और "Click here to apply now" क्लिक करें' },
      { en: 'Select "Self Enrollment" if applying yourself, or visit nearest CSC center', hi: '"Self Enrollment" चुनें अगर खुद आवेदन कर रहे हैं, या नजदीकी CSC केंद्र जाएं' },
      { en: 'Enter Mobile Number → Verify OTP → Create account with password', hi: 'मोबाइल नंबर दर्ज करें → OTP सत्यापित करें → पासवर्ड से खाता बनाएं' },
      { en: 'Enter Aadhaar Number and verify your identity', hi: 'आधार नंबर दर्ज करें और अपनी पहचान सत्यापित करें' },
      { en: 'Fill personal details — Name, Date of Birth, State, District, Village', hi: 'व्यक्तिगत विवरण भरें — नाम, जन्म तिथि, राज्य, जिला, गांव' },
      { en: 'Enter Bank Account Number and IFSC Code for auto-debit of contribution', hi: 'ऑटो-डेबिट के लिए बैंक खाता नंबर और IFSC कोड दर्ज करें' },
      { en: 'Monthly contribution is auto-calculated based on your age (₹55 at 18 to ₹200 at 40)', hi: 'मासिक योगदान आपकी उम्र के आधार पर स्वचालित (18 पर ₹55 से 40 पर ₹200)' },
      { en: 'Confirm enrollment and save your Pension Card / PRAN number', hi: 'नामांकन की पुष्टि करें और अपना पेंशन कार्ड / PRAN नंबर सहेजें' },
      { en: 'Monthly contribution auto-debited from bank. After age 60, get ₹3,000/month pension.', hi: 'मासिक योगदान बैंक से ऑटो-डेबिट। 60 वर्ष बाद ₹3,000/माह पेंशन।' },
    ],
  },
  {
    name: 'National Mission on Oilseeds & Oil Palm (NMOOP)', benefit: '₹30,000/ha', status: 'Active',
    desc: 'Financial assistance for planting oil palm, soybean, groundnut, mustard. Seed, fertilizer & mechanization support.',
    descHi: 'तिलहन और तेल ताड़ रोपण के लिए वित्तीय सहायता। बीज, उर्वरक और यंत्रीकरण सहायता।',
    elig: 'Farmers in identified districts growing oilseed crops',
    eligHi: 'तिलहन फसल उगाने वाले चिन्हित जिलों के किसान',
    docs: ['Land Records', 'Aadhaar', 'Crop Plan'],
    ministry: 'Ministry of Agriculture', deadline: '30 Sep 2026',
    applyUrl: 'https://nmoop.gov.in',
    steps: [
      { en: 'Visit nmoop.gov.in and check if your district is covered under the mission', hi: 'nmoop.gov.in पर जाएं और जांचें कि आपका जिला मिशन में शामिल है या नहीं' },
      { en: 'Contact your District Agriculture Office or Block Development Officer', hi: 'अपने जिला कृषि कार्यालय या खंड विकास अधिकारी से संपर्क करें' },
      { en: 'Submit application with land records and proposed crop plan (oil palm/soybean/groundnut)', hi: 'भूमि रिकॉर्ड और प्रस्तावित फसल योजना (तेल ताड़/सोयाबीन/मूंगफली) के साथ आवेदन जमा करें' },
      { en: 'Select the component — oil palm planting, oilseed seeds, or farm mechanization', hi: 'घटक चुनें — तेल ताड़ रोपण, तिलहन बीज, या कृषि यंत्रीकरण' },
      { en: 'Provide Aadhaar, bank passbook copy, and land ownership documents', hi: 'आधार, बैंक पासबुक कॉपी और भूमि स्वामित्व दस्तावेज़ प्रदान करें' },
      { en: 'Attend training programs organized by the mission (if applicable)', hi: 'मिशन द्वारा आयोजित प्रशिक्षण कार्यक्रमों में भाग लें (यदि लागू हो)' },
      { en: 'Plant the approved oilseed crop and submit progress reports to the office', hi: 'स्वीकृत तिलहन फसल लगाएं और कार्यालय को प्रगति रिपोर्ट जमा करें' },
      { en: 'Subsidy up to ₹30,000/ha disbursed after field verification by agriculture officer', hi: 'कृषि अधिकारी द्वारा क्षेत्र सत्यापन के बाद ₹30,000/हेक्टेयर तक सब्सिडी वितरित' },
    ],
  },
];

export default schemes;

